### ISSUE TITLE
学习率初始化值问题

### ISSUE THREAD

**Issue by kurie21** [ZK-Zhou/spikformer#10]
您好，您在论文中提到，在cifar10dvs与128dvs上：“The learning rate is initialized to 0.1”，但在train.py中lr使用的是0.001。我使用0.1的学习率对在cifar10dvs上训练，没有办法收敛；但用0.001的学习率训练时，复现结果与您论文相差不大。想问一下，您实际用的lr是多少呢？在论文中提到的lr为0.1是笔误吗？

**Comment by ZK-Zhou** [comment]
您好，以代码为准

**Comment by kurie21** [comment]
好的，谢谢！
