### ISSUE TITLE
Fail to reproduce the Spikformer-4-256 on CIFAR-10

### ISSUE THREAD

**Issue by kurie21** [ZK-Zhou/spikformer#13]
Hi dear authors, 

Sorry for bothering you again. While training the Spikformer-4-256 model on CIFAR-10, I encountered a problem with the following error message: "AssertionError: dim 256 should be divided by num_heads 12."

I am seeking assistance to resolve this issue and was wondering if you could provide information regarding the value of num_heads used during your experiment. Any insights you can offer would be greatly appreciated.

Thank you very much for your time and assistance.

**Comment by QianpengLi577** [comment]
Try 8 heads. 
The best metric is about 94.

**Comment by kurie21** [comment]
Thanks!!
