### ISSUE TITLE
The training code for CIFAR10-DVS dataset.

### ISSUE THREAD

**Issue by qianyu0220** [ZK-Zhou/spikformer#2]
Hi Zhaokun. Thank you so much for providing the code for this work. Could you please share the training code for CIFAR10-DVS dataset? That would be very useful for my research. Thanks!!

**Comment by ZK-Zhou** [comment]
Thank you for your attention, I am sorting this code and uploading it as soon as possible.

**Comment by ZK-Zhou** [comment]
spikformer code for  CIFAR10dvs  has been uploaded.

**Comment by qianyu0220** [comment]
> spikformer code for CIFAR10dvs has been uploaded.

Thank you so much!!
