### ISSUE TITLE
No module named 'sj_dropout'

### ISSUE THREAD

**Issue by chococheri** [ZK-Zhou/spikformer#3]
Hi Dr. Zhou! A series of problems occurred when I run the "cifar10/train.py". 

1. model cannot be imported into train.py, it shows a grey color
2. In model.py, there is an error "No module named 'sj_dropout' ". I have already searched on the internet but cannot find what the sj_dropout is. 

`Traceback (most recent call last):
  File "/home/PycharmProjects/spikformer/cifar10/train.py", line 42, in <module>
    import model
  File "/home/PycharmProjects/spikformer/cifar10/model.py", line 9, in <module>
    from sj_dropout import SN_Droppath
ModuleNotFoundError: No module named 'sj_dropout'
`
Waiting for your reply!  Thank you!

**Comment by ZK-Zhou** [comment]
it is a drop-path file. Just Delete it.
