### ISSUE TITLE
No checkpoint found at '/home/.../svit-8-512.pth.tar'

### ISSUE THREAD

**Issue by YangSkywalker** [ZK-Zhou/spikformer#4]
Hello, ZK-Zhou,

Could you tell me how to deal with the error " No checkpoint found at '/home/zhou/new_desk/Transformer-SNN/imagenet/src_5/pretrained/svit-8-512.pth.tar'"?

Thank you very much!

**Comment by ZK-Zhou** [comment]
Hi，you need to train the weights first, and then evaluate them using test file.

**Comment by ZK-Zhou** [comment]
Sorry for late reply, you can delate the resume in yml file and rerun the train.py file. Our pre-trained models are base on old-version code base so we do not provide them.

**Comment by navfour** [comment]
不好意思，周末没有打开git。谢谢您的耐心解答
