### ISSUE TITLE
数据处理

### ISSUE THREAD

**Issue by whz-snn** [ZK-Zhou/spikformer#9]
从download->extract 的aedat格式是正常，本应该extract/xx/xx.aedat->events_up/xx/xx.npz，结果现在events_up/xx是空的文件夹，没有npz，尝试换台机器跑也是这个问题。

**Comment by ZK-Zhou** [comment]
You can delete the processed data folder and try again.

**Comment by whz-snn** [comment]
感谢答复，这个应该是spikingjelly的原因，我在它的issue中发现了同类问题。


  还有一些看论文时的遇到的问题。

  1.Table one 你对比了A_I 、A_RELU 、A_leakyRelu 、A_softmax 、A_SSA 其中前4个的QK是float V是spike，最后SSA的QKV都是spike，是这样的吧，这样让QK是float的意义是什么；

  2.如果是这样的话，QK如何保持float，是有一个从输入直接到attention的分支吗，按照我的理解，经过了SPS模块的话，都会变成spike；

  3.为什么要设置和relu对比的，softmax对比的实验可以理解，因为VSA是softmax，所以我理解的可能设置的实验是VSA的float QKV和SSA的spike QKV对比就可以说明SSA的显著优势？


-----原始邮件-----
发件人:"Zhaokun Zhou" ***@***.***>
发送时间:2023-06-02 22:23:27 (星期五)
收件人: ZK-Zhou/spikformer ***@***.***>
抄送: whz-snn ***@***.***>, Author ***@***.***>
主题: Re: [ZK-Zhou/spikformer] 数据处理 (Issue #9)






You can delete the processed data folder and try again.

**Comment by ZK-Zhou** [comment]
Hi，
1. Yep, Q, K, and V are all spike-form. In the first four variant, we test whether the float-point Q,K can improve the performance.
2. Just cancel the spiking neuron in SSA we can get the float-point Q,K
3. The more, The better :). No reviewer will criticize you for doing too many experiments
